name: Tests (Windows)

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test-suite.yml
    with:
      os: windows-2022
